spring:
  data:
    mongodb:
      authentication-database: none
      database: document_db
      port: 27017
      host: localhost
mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - com.sivtcev.purchaseSaveService.changelog